add Entrypoint method to remote and local images
buildpacks/imgutil pull request #90
Opened 2021-02-04 05:39 UTC by dwillist

This would be helpful for `pack` when determining the entrypoint process which is needed to resolve [this `pack` issue](https://github.com/buildpacks/pack/issues/1034)

Signed-off-by: dwillist <dthornton@vmware.com>

2021-02-04 15:42 UTC, ekcasey requested changes

2021-02-04 15:42 UTC, ekcasey commented on local/local.go
> +}
```suggestion
func (i *Image) Entrypoint() ([]string, error) {
	return i.inspect.Config.Entrypoint, nil
}
```
Given the image can technically have either a `nulll` or empty entrypoint I don't think we should translate null to empty and should instead just return the value.

2021-02-04 15:42 UTC, ekcasey commented on remote/remote.go
> +	return cfg.Config.Entrypoint, nil
```suggestion
	return cfg.Config.Entrypoint, nil
```
See comment above.

2021-02-04 15:42 UTC, ekcasey commented on remote/remote.go
> +		return []string{}, fmt.Errorf("failed to get config file for image '%s'", i.repoName)
```suggestion
		return nil, fmt.Errorf("failed to get config file for image '%s'", i.repoName)
```

2021-02-09 12:53 UTC, dfreilich approved these changes

2021-02-09 15:57 UTC, ekcasey approved these changes

2021-02-09 15:57 UTC, ekcasey commented on local/local_test.go
> +			it("returns an empty slice for a missing entrypoint", func() {
```suggestion
			it("returns a nil slice for a missing entrypoint", func() {
```

2021-02-09 15:57 UTC, ekcasey commented on local/local_test.go
> +			it("returns an empty slice", func() {
```suggestion
			it("returns a nil slice", func() {
```

2021-02-09 15:57 UTC, ekcasey commented on remote/remote_test.go
> +			it("returns an empty slice for a missing entrypoint", func() {
```suggestion
			it("returns a nil slice for a missing entrypoint", func() {
```

2021-02-09 15:57 UTC, ekcasey commented on remote/remote_test.go
> +			it("returns an empty slice", func() {
```suggestion
			it("returns a nile slice", func() {
```

2021-02-09 16:01 UTC, dfreilich commented on remote/remote_test.go
> +			it("returns an empty slice", func() {
nil*

2021-02-09 16:36 UTC, merged